### ISSUE TITLE
Table of sub product without Item No. is shifted

### ISSUE THREAD

**Issue by akasjain2** [aemsites/octoral#105]
https://issue99--octoral--aemsites.hlx.live/en/products/non-voc/thinners

Product **TH730 HS Thinner Very Slow** has a missing Item nr. Due to this the table headers are shifted.

<img width="1378" alt="Screenshot 2024-09-11 at 10 18 02 AM" src="https://github.com/user-attachments/assets/02d00644-df7b-4942-b9bc-e07b1d77cbbb">

**Comment by dave-fink** [comment]
@akasjain2 Good catch! Let's just use the main branch to identify bugs 
https://main--octoral--aemsites.hlx.live/en/products/non-voc/thinners 

@meejain  I'm guessing this is a data (excel issue), not sure.  However is there anything we can do in code to prevent it from breaking the table?
