### ISSUE TITLE
Missing metadata

### ISSUE THREAD

**Issue by dave-fink** [aemsites/octoral#111]
Some pages are missing metadata and not showing an accurate page title.

Example: https://octoral.com/en/support/colour-retrieval/tinting-guide/
![image](https://github.com/user-attachments/assets/f00c9381-fec4-441b-b259-be6079df7e02)
 
In cases where we do not have any metadata let's include this table:

![image](https://github.com/user-attachments/assets/467e96ca-fa76-4a4e-9fd4-aa098d019e3f)

Please include the empty description and image rows, as Authors may want to update these in the future.

**Comment by akasjain2** [comment]
Fixed all pages. Pages with missing metadata included support, colour retrieval, contact and news list page.
