### ISSUE TITLE
[Template] News list

### ISSUE THREAD

**Issue by akasjain2** [aemsites/octoral#21]
News list page exists for each language.

https://www.octoral.com/en/news
https://www.octoral.com/nl/nieuws
https://www.octoral.com/de/nachrichten
https://www.octoral.com/fr/nouvelles
https://www.octoral.com/it/novita
https://www.octoral.com/es/noticia

<img width="834" alt="EN News list page" src="https://github.com/user-attachments/assets/675664ba-6494-4a75-8d2d-8bde6e30f96f">

**Comment by tmorris-adobe** [comment]
This is complete
