### ISSUE TITLE
Metadata for news list

### ISSUE THREAD

**Issue by akasjain2** [aemsites/octoral#44]
News list page will fetch content from a metadata file. This file is populated from the metadata of individual news pages.
The scope of this task is to set correct metadata elements in the news article docx file.

**Comment by dave-fink** [comment]
@akasjain2 I believe we should have what we need to create the news-index needed for the list page.  

Elements needed for list page:

- Title - get from H1
- Intro Text - we can grab from first paragraph on the page (Confirmed with Lindsey in Slack and on our weekly call)
- PublishedDate - already in metadata, used for sorting

@tmorris-adobe if you find anything that is needed please let Akash know, I'm assigning this to you till we close out the list page.

**Comment by akasjain2** [comment]
Add image to the news document metadata.
