### ISSUE TITLE
News List Page Clip text at 3 lines for each article

### ISSUE THREAD

**Issue by dave-fink** [aemsites/octoral#69]
For the news list page clip the text at 3 lines and show an ellipsis (...).

- Pull the entire first paragraph into the index
- In CSS we can limit the text to the first 3 lines - https://www.w3schools.com/cssref/css3_pr_text-overflow.php

<img width="681" alt="image" src="https://github.com/user-attachments/assets/57a622dc-f472-476b-8778-73f1e7518a26">

**Comment by tmorris-adobe** [comment]
this is complete
