### ISSUE TITLE
Update New-list pages to handle all locales  

### ISSUE THREAD

**Issue by dave-fink** [aemsites/octoral#88]
The news pages appear across all languages, we need to update the news-list javascript to get the locale and then fetch the correct news articles.  We'll also need to adjust the page title accordingly.  

We will need to update the `helix-query.yaml` file and add all the other news locales to it.  Once they've been added we'll need to re-publish the pages so they get added to the indexes. 

Let's also add redirects in the redirects.xlsx spreadsheet since the old path did not include a `/` 
![image](https://github.com/user-attachments/assets/50a75b43-316c-4bb4-80b9-519f5f9a025b)

https://main--octoral--aemsites.hlx.page/nl/nieuws/
https://main--octoral--aemsites.hlx.page/de/nachrichten/
https://main--octoral--aemsites.hlx.page/fr/nouvelles/
https://main--octoral--aemsites.hlx.page/it/novita/
https://main--octoral--aemsites.hlx.page/es/noticia/

**Comment by tmorris-adobe** [comment]
redirects added to redirects.xlsx for the following locales:

/nl/nieuws/
/de/nachrichten/
/fr/nouvelles/
/it/novita/
/es/noticia/

**Comment by tmorris-adobe** [comment]
This is complete
